/*
 * JSP generated by Resin-3.1.4 (built Tue, 04 Dec 2007 05:30:53 PST)
 */

package _jsp._web_22dinf._views._base;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _savebasedatadialog__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_5.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      pageContext.include("../common.jsp", false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -5502314496210410653L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.id }");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.name }");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.name_en }");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.icon }");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.url }");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseData.typeId }");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/views/base/saveBaseDataDialog.jsp"), -6287818434054628641L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;

  private final static char []_jsp_string14;
  private final static char []_jsp_string6;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string12;
  private final static char []_jsp_string5;
  private final static char []_jsp_string11;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string13;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  static {
    _jsp_string14 = "/js/common.js\"></script>\r\n<script type=\"text/javascript\">\r\n	initajaxupload(\"upload\",\"/imgupload/upload.jsps?direct=case\",afterupload,null,null);\r\n	\r\n	function afterupload(json,data){\r\n		if(json.STATE=='SUCCESS'){\r\n			\r\n			art.dialog.alert(\"\u4e0a\u4f20\u6210\u529f\",function(){\r\n				$(\"#icon\").val(json.PATH);\r\n			});\r\n			\r\n		}else{\r\n			art.dialog.alert(\"\u4e0a\u4f20\u5931\u8d25\");\r\n		}\r\n	}\r\n</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string6 = "\"/>\r\n\r\n<form id=\"saveBaseTypeForm\">\r\n</form>\r\n<div style=\"clear:both\"></div>\r\n<input id=\"upload\" type=\"button\" value=\"\u6dfb\u52a0\u56fe\u6807\"/>\r\n".toCharArray();
    _jsp_string10 = "/js/ligerUI/js/plugins/ligerComboBox.js\" type=\"text/javascript\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n<html>\r\n<head>\r\n<title>\u4fee\u6539\u57fa\u7840\u7c7b\u578b</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n\r\n</head>\r\n<body>\r\n<input type=\"hidden\" id=\"dataId\" value=\"".toCharArray();
    _jsp_string2 = "\"/>\r\n<input type=\"hidden\" id=\"name_enId\" value=\"".toCharArray();
    _jsp_string7 = "\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string12 = "/js/custom/base/saveBaseDataDialog.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string5 = "\"/>\r\n<input type=\"hidden\" id=\"typeId\" value=\"".toCharArray();
    _jsp_string11 = "/js/ligerUI/js/plugins/ligerDateEditor.js\" type=\"text/javascript\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string8 = "/js/ligerUI/js/plugins/ligerForm.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string1 = "\"/>\r\n<input type=\"hidden\" id=\"nameId\" value=\"".toCharArray();
    _jsp_string9 = "/js/ligerUI/js/plugins/ligerTextBox.js\" type=\"text/javascript\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string13 = "/js/ajaxupload.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string3 = "\"/>\r\n<input type=\"hidden\" id=\"iconId\" value=\"".toCharArray();
    _jsp_string4 = "\"/>\r\n<input type=\"hidden\" id=\"urlId\" value=\"".toCharArray();
  }
}
