/*
 * JSP generated by Resin-3.1.4 (built Tue, 04 Dec 2007 05:30:53 PST)
 */

package _jsp._web_22dinf._views._product;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _openproductdialog__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (_caucho_expr_3.evalBoolean(_jsp_env)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_caucho_expr_4.evalBoolean(_jsp_env)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if (_caucho_expr_5.evalBoolean(_jsp_env)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.lang.Object _jsp_items_1 = _caucho_expr_6.evalObject(_jsp_env);
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_1);
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("item", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _caucho_expr_7.print(out, _jsp_env, false);
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_8.evalBoolean(_jsp_env)) {
          out.write(_jsp_string10, 0, _jsp_string10.length);
        }
        out.write('>');
        _caucho_expr_9.print(out, _jsp_env, false);
        out.write(_jsp_string11, 0, _jsp_string11.length);
      }
      pageContext.removeAttribute("item");
      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      if (_caucho_expr_11.evalBoolean(_jsp_env)) {
        out.write(_jsp_string14, 0, _jsp_string14.length);
        _caucho_expr_12.print(out, _jsp_env, false);
        out.write(_jsp_string15, 0, _jsp_string15.length);
        _caucho_expr_13.print(out, _jsp_env, false);
        out.write(_jsp_string16, 0, _jsp_string16.length);
      }
      out.write(_jsp_string17, 0, _jsp_string17.length);
      pageContext.include("../common.jsp", false);
      out.write(_jsp_string18, 0, _jsp_string18.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string19, 0, _jsp_string19.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string20, 0, _jsp_string20.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string21, 0, _jsp_string21.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string22, 0, _jsp_string22.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string23, 0, _jsp_string23.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string24, 0, _jsp_string24.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string25, 0, _jsp_string25.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string26, 0, _jsp_string26.length);
      _caucho_expr_12.print(out, _jsp_env, false);
      out.write(_jsp_string27, 0, _jsp_string27.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -5502314496210410653L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.id }");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.name }");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.desc }");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.typeId==1 }");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.typeId==2 }");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.typeId==3 }");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${serials }");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.id }");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.basedataId==item.id }");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.name }");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.mainPhoto }");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${! empty product.mainPhoto }");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${product.mainPhoto}");
    _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base }");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/views/product/openProductDialog.jsp"), 7103007299220027565L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;

  private final static char []_jsp_string23;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string26;
  private final static char []_jsp_string21;
  private final static char []_jsp_string19;
  private final static char []_jsp_string13;
  private final static char []_jsp_string9;
  private final static char []_jsp_string24;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string22;
  private final static char []_jsp_string6;
  private final static char []_jsp_string18;
  private final static char []_jsp_string27;
  private final static char []_jsp_string25;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  private final static char []_jsp_string20;
  private final static char []_jsp_string1;
  private final static char []_jsp_string17;
  private final static char []_jsp_string15;
  private final static char []_jsp_string12;
  private final static char []_jsp_string16;
  private final static char []_jsp_string14;
  static {
    _jsp_string23 = "/js/ligerUI/js/plugins/ligerDateEditor.js\"\r\n		type=\"text/javascript\"></script>\r\n	<script type=\"text/javascript\"\r\n		src=\"".toCharArray();
    _jsp_string3 = "\"/>\r\n	<form id=\"saveProductForm\">\r\n		\r\n	</form>\r\n	<div style=\"clear:both\"></div>\r\n	<div style=\"padding-left:20px;\">\r\n	<label>\r\n	<input type=\"radio\" name=\"baseType\" value=\"1\" ".toCharArray();
    _jsp_string11 = "</option>\r\n		".toCharArray();
    _jsp_string26 = "/js/common.js\"></script>\r\n<script type=\"text/javascript\">\r\n	initajaxupload(\"upload\",\"/imgupload/upload.jsps?direct=product\",afterupload,null,null);\r\n	\r\n	function afterupload(json,data){\r\n		if(json.STATE=='SUCCESS'){\r\n			art.dialog.tips(\"\u4e0a\u4f20\u6210\u529f\");\r\n			var html = \"<img style='width:200px;' src='".toCharArray();
    _jsp_string21 = "/js/ligerUI/js/plugins/ligerTextBox.js\"\r\n		type=\"text/javascript\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string19 = "/js/ligerUI/js/core/base.js\"\r\n		type=\"text/javascript\"></script>\r\n	<script type=\"text/javascript\"\r\n		src=\"".toCharArray();
    _jsp_string13 = "\"/>\r\n	<input id=\"upload\" type=\"button\" value=\"\u6dfb\u52a0\u56fe\u7247\"/>\r\n	<div id=\"imgdiv\">\r\n	".toCharArray();
    _jsp_string9 = "\" ".toCharArray();
    _jsp_string24 = "/js/custom/product/saveProductDialog.js\"></script>\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string7 = " />\r\n	\u4ea7\u54c1\u8be6\u60c5\r\n	</label>\r\n	</div>\r\n	<div style=\"margin-top:5px;margin-left:20px;\">\r\n	\u4ea7\u54c1\u7c7b\u522b:\r\n	<select id=\"serials\" style=\"width:150px;\">\r\n		".toCharArray();
    _jsp_string2 = "\"/>\r\n	<input type=\"hidden\" id=\"productDesc\" value=\"".toCharArray();
    _jsp_string22 = "/js/ligerUI/js/plugins/ligerComboBox.js\"\r\n		type=\"text/javascript\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string6 = " />\r\n	\u4ea7\u54c1\r\n	</label>\r\n	<label>\r\n	<input type=\"radio\" name=\"baseType\" value=\"3\" ".toCharArray();
    _jsp_string18 = "\r\n	<script src=\"".toCharArray();
    _jsp_string27 = "/uploadimages/\"+json.PATH+\"'/>\";\r\n			$(\"#imgdiv\").html(html);\r\n			\r\n			$(\"#mainPhoto\").val(json.PATH);\r\n			\r\n		}else{\r\n			art.dialog.alert(\"\u4e0a\u4f20\u5931\u8d25\");\r\n		}\r\n	}\r\n</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string25 = "/js/ajaxupload.js\"></script>\r\n		<script type=\"text/javascript\" src=\"/js/artDialog/artDialog.js?skin=blue\"></script>\r\n<script type=\"text/javascript\" src=\"/js/artDialog/plugins/iframeTools.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n<html>\r\n<head>\r\n<title>\u4fee\u6539\u4ea7\u54c1</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n\r\n</head>\r\n<body>\r\n	<input type=\"hidden\" id=\"productId\" value=\"".toCharArray();
    _jsp_string8 = "\r\n			<option value=\"".toCharArray();
    _jsp_string10 = "selected".toCharArray();
    _jsp_string5 = " />\r\n	\u9996\u9875\r\n	</label>\r\n	<label>\r\n	<input type=\"radio\" name=\"baseType\" value=\"2\" ".toCharArray();
    _jsp_string4 = "checked".toCharArray();
    _jsp_string20 = "/js/ligerUI/js/plugins/ligerForm.js\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string1 = "\"/>\r\n	<input type=\"hidden\" id=\"productName\" value=\"".toCharArray();
    _jsp_string17 = "\r\n	</div>\r\n	".toCharArray();
    _jsp_string15 = "/uploadimages/".toCharArray();
    _jsp_string12 = "\r\n	</select>\r\n	</div>\r\n	<div style=\"clear:both;\">\r\n	</div> \r\n	<input type=\"hidden\" id=\"mainPhoto\" name=\"mainPhoto\" value=\"".toCharArray();
    _jsp_string16 = "'/>\r\n		".toCharArray();
    _jsp_string14 = "\r\n		<img style='width:200px;' src='".toCharArray();
  }
}
